package abc;
import java.util.ArrayList;

public class Admin extends User implements Reportable {

    public Admin(int id, String name, String email, String password) {
        super(id, name, email, password, "Admin");
    }

    @Override
    public void displayRole() {
        System.out.println("Role: Admin");
    }

    @Override
    public void generateReport() {
        System.out.println("==========================================");
        System.out.println("       CAMPUS SUSTAINABILITY REPORT       ");
        System.out.println("==========================================");
        System.out.println("Report generated by : " + getName());
        System.out.println("SDG Goal 13         : Climate Action");
        System.out.println("Campus              : Taylor's University");
        System.out.println("==========================================");
    }

    public void generateReport(ArrayList<GreenActivity> activities) {
        generateReport();
        int total    = activities.size();
        int totalPts = 0;
        int cycling  = 0, electricity = 0, recycling = 0, other = 0;

        for (int i = 0; i < activities.size(); i++) {
            String t = activities.get(i).getActivityType();
            totalPts += activities.get(i).getPoints();
            if (t.equals("Cycling"))     cycling++;
            else if (t.equals("Electricity")) electricity++;
            else if (t.equals("Recycling"))   recycling++;
            else other++;
        }

        System.out.println("Total Activities Logged : " + total);
        System.out.println("Total Points Earned     : " + totalPts);
        System.out.println("------------------------------------------");
        System.out.println("Cycling     : " + cycling);
        System.out.println("Electricity : " + electricity);
        System.out.println("Recycling   : " + recycling);
        System.out.println("Other       : " + other);
        System.out.println("==========================================");
    }

    public void viewAllActivities(ArrayList<GreenActivity> activities) {
        if (activities.size() == 0) {
            System.out.println("No activities logged yet.");
            return;
        }
        System.out.println("==========================================");
        System.out.println("         ALL GREEN ACTIVITIES             ");
        System.out.println("==========================================");
        int totalPoints = 0;
        for (int i = 0; i < activities.size(); i++) {
            System.out.println("Activity #" + (i + 1));
            System.out.println("  Activity ID : " + activities.get(i).getActivityID());
            System.out.println("  Type        : " + activities.get(i).getActivityType());
            System.out.println("  Date        : " + activities.get(i).getDate());
            System.out.println("  Points      : " + activities.get(i).getPoints());
            System.out.println("------------------------------------------");
            totalPoints += activities.get(i).getPoints();
        }
        System.out.println("Total Points : " + totalPoints);
        System.out.println("==========================================");
    }

    public void viewAllUsers(ArrayList<User> users) {
        System.out.println("==========================================");
        System.out.println("            ALL REGISTERED USERS          ");
        System.out.println("==========================================");
        for (int i = 0; i < users.size(); i++) {
            System.out.println("User #" + (i + 1));
            System.out.println("  ID    : " + users.get(i).getUserID());
            System.out.println("  Name  : " + users.get(i).getName());
            System.out.println("  Email : " + users.get(i).getEmail());
            System.out.println("  Role  : " + users.get(i).getRole());
            System.out.println("------------------------------------------");
        }
    }
}